Login nav bar
Tresky/event-web pull request #1
Opened 2017-01-29 00:22 UTC by TylerGauntlett

2017-01-29 04:07 UTC, Tresky requested changes

2017-01-29 04:07 UTC, Tresky commented on src/app/components/login/loginStyles.styl
> +body {
Will you convert this to Stylus syntax and nest whatever can be nested?

2017-01-29 04:07 UTC, Tresky commented on src/app/components/home/homeStyles.styl
> +}
Will you convert this one to Stylus as well? The brackets is the only thing.

2017-01-29 04:07 UTC, Tresky commented on src/app/shared/navBar/navBarDirective.js
> +)
Does this directive have a parameter on it called 'flag'? If not, let's take it out before committing it.

2017-01-29 04:07 UTC, Tresky commented on src/app/shared/navBar/navBarStyles.styl
> +}
Brackets :P

2017-01-29 04:07 UTC, Tresky commented on src/public/index.html
>  </html>
Did you get this to work without reordering the JS items? If so, that's super awesome!

2017-02-01 18:01 UTC, TylerGauntlett commented on src/app/components/login/loginStyles.styl
> +body {
Done

2017-02-01 18:01 UTC, TylerGauntlett commented on src/app/components/home/homeStyles.styl
> +}
Done

2017-02-01 18:01 UTC, TylerGauntlett commented on src/app/shared/navBar/navBarDirective.js
> +)
Done

2017-02-01 18:04 UTC, TylerGauntlett commented on src/public/index.html
>  </html>
Ended up needed jquery first but could remove teather as we are using bootstrap 3 again.

2017-02-01 18:05 UTC, TylerGauntlett commented on src/app/shared/navBar/navBarStyles.styl
> +}
Done

2017-02-01 20:03 UTC, Tresky approved these changes

2017-02-01 20:26 UTC, merged