Added dashboard page. This allows you to view your subscribed rsos ev…
Tresky/event-web pull request #12
Opened 2017-03-21 06:17 UTC by TylerGauntlett

…ents, make new events, make rsos and join/leave rsos

2017-03-21 19:02 UTC, Tresky requested changes

2017-03-21 19:02 UTC, Tresky commented on src/app/components/dashboard/dashboardView.html
> +              <td>Face Painting</td>
Is this is hardcoded event data?

2017-03-21 19:02 UTC, Tresky commented on src/app/components/dashboard/dashboardView.html
> +                  <label for="rso-lead-email">RSO Leader Email:</label>
Let's not have an RSO leader email, but instead just have the four other emails. The RSO leader will be assumed to be the person who filled out the form.

2017-03-24 00:40 UTC, TylerGauntlett commented on src/app/components/dashboard/dashboardView.html
> +              <td>Face Painting</td>
Yes all hard coded.

2017-03-24 00:41 UTC, TylerGauntlett commented on src/app/components/dashboard/dashboardView.html
> +                  <label for="rso-lead-email">RSO Leader Email:</label>
Rereading the docs, i think you need 5 people PLUS you. Ill double check though.

2017-03-24 04:44 UTC, TylerGauntlett commented on src/app/components/dashboard/dashboardView.html
> +                  <label for="rso-lead-email">RSO Leader Email:</label>
`A new RSO can be created with at least 5 other students with the same email domain, e.g.@knights.ucf.edu; and one of them should be assigned as an administrator.` from doc

2017-03-24 04:53 UTC, Tresky commented on src/app/components/dashboard/dashboardView.html
> +              <td>Face Painting</td>
I'm assuming this is not permanent. lol

2017-03-24 04:54 UTC, Tresky commented on src/app/components/dashboard/dashboardView.html
> +                  <label for="rso-lead-email">RSO Leader Email:</label>
So, we need 6 people?

2017-03-31 04:00 UTC, TylerGauntlett commented on src/app/components/dashboard/dashboardView.html
> +              <td>Face Painting</td>
Its all just html right now. Made the views as quickly as possible so Koha always had something to work on. Will add functionality this weekend.

2017-03-31 04:00 UTC, TylerGauntlett commented on src/app/components/dashboard/dashboardView.html
> +                  <label for="rso-lead-email">RSO Leader Email:</label>
Did exactly that

2017-03-31 04:18 UTC, Tresky approved these changes

2017-04-01 00:12 UTC, merged