Static event page template. No logic, strictly view.
Tresky/event-web pull request #4
Opened 2017-02-04 20:43 UTC by TylerGauntlett

2017-02-04 20:50 UTC, Tresky requested changes

2017-02-04 20:50 UTC, Tresky commented on src/app/index.js
> +        })
Could you line this up with the states above it?

2017-02-04 20:50 UTC, Tresky commented on src/app/styles/index.styl
> +@import 'global'
Place these in alphabetical order

2017-02-04 20:50 UTC, Tresky commented on src/public/index.html
> +    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" cross
CSS should be loaded in the <head> of the document. Might even be good to group it in with the normal JSDelivr of whatever stylesheets we loading from them.

2017-02-04 20:50 UTC, Tresky commented on src/app/components/index.js
>  import './login/loginController.js'
Alphabetical order

2017-02-04 20:50 UTC, Tresky commented on src/app/components/event/eventController.js
> +)
This file needs to be imported in the `controllers/index.js`

2017-02-09 01:43 UTC, TylerGauntlett commented on src/app/index.js
> +        })
Done

2017-02-09 01:44 UTC, TylerGauntlett commented on src/app/styles/index.styl
> +@import 'global'
Done

2017-02-09 01:46 UTC, TylerGauntlett commented on src/public/index.html
> +    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" cross
Move it near the other css include

2017-02-09 01:46 UTC, TylerGauntlett commented on src/app/components/index.js
>  import './login/loginController.js'
Done

2017-02-09 01:51 UTC, TylerGauntlett commented on src/app/components/event/eventController.js
> +)
Added to `controllers/index.js`

2017-02-09 02:01 UTC, Tresky approved these changes

2017-02-09 21:29 UTC, merged